
dataset: &dataset cifar100
init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 100
task_num: &task_num 5
image_size: &image_size 32

init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
task_num: *task_num

epoch: 250
stage2_epoch: 250
val_per_epoch: 250
batch_size: 128

testing_times: 1

num_workers: 0

train_trfms:
  - RandomHorizontalFlip: {}
  - RandomCrop: 
      size : *image_size
      padding : 4
  - ToTensor: {}
  - Normalize:
      mean: [0.5071, 0.4866, 0.4409]
      std: [0.2673, 0.2564, 0.2762]

test_trfms: 
  - ToTensor: {}
  - Normalize:
      mean: [0.5071, 0.4866, 0.4409]
      std: [0.2673, 0.2564, 0.2762]

optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 2e-4

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [100, 150, 200]

# done
backbone:
  name: resnet18 # cifar_resnet32_V2 
  kwargs:
    num_classes: *total_cls_num
    args: 
      dataset: *dataset

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
    strategy: herding      # random, equal_random, reservoir, herding 

classifier:
  name: bic
  kwargs:
    num_class: *total_cls_num
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    feat_dim: 512 # 64 