# For logger
save_path : ""

data_root: "../dataset/cifar-dataset/cifar100" #data path, where is your data

# init_cls_num = inc_cls_num
# task_num = total class / inc_cls_num
# buffer capacity = num_classes * 20

task_num: 20 #任务数量
init_cls_num: 5 # 第一次任务的分类数量
inc_cls_num: 5 #之后每次任务的分类数量
init_epoch: 15 # init_epoch
epoch: 15 # inc_epoch
batch_size: 32

device_ids: 0

optimizer:
  name: SGD
  kwargs:
    lr: 0.1

lr_scheduler:
  name: StepLR
  kwargs:
    gamma: 0.5
    step_size: 10

buffer:
  name: ERBuffer
  kwargs:
    capacity: 2000
    input_size: (3, 32, 32)

backbone: 
  name: resnet18
  kwargs:
    args: 
      dataset: cifar100

classifier:
  name: ERACE
  kwargs:
    num_classes: 100
    task_free: False
