# 10-subsets on CiFar100
#task_num: 10 
#init_cls_num: 10 
#inc_cls_num: 10 

# 20-subsets on CiFar100
task_num: 5
init_cls_num: 20 
inc_cls_num: 20

init_epoch: 1
epoch: 1
val_per_epoch: 1

batch_size: 10 # 10, don't set too high, otherwise performance will drop

optimizer:
  name: SGD
  kwargs:
    lr: 0.01

buffer:
  name: ERBuffer
  kwargs:
    capacity: 10000 # num_classes * 20
    input_size: (3, 32, 32)

backbone: 
  name: resnet18
  kwargs:
    args: 
      dataset: cifar100

classifier:
  name: ERACE
  kwargs:
    num_classes: 100
    task_free: False
