# 10-subsets on CiFar100
#task_num: 10 
#init_cls_num: 10 
#inc_cls_num: 10 

# 20-subsets on CiFar100
task_num: 20
init_cls_num: 5 
inc_cls_num: 5

init_epoch: 1
epoch: 1
val_per_epoch: 1

batch_size: 10
testing_times: 1

train_trfms:
  - ToTensor: {}
  - Normalize:
      mean: [0.5071,  0.4866,  0.4409]
      std: [0.2675, 0.2565, 0.2761]

test_trfms: 
  - ToTensor: {}
  - Normalize:
      mean: [0.5071,  0.4866,  0.4409]
      std: [0.2675, 0.2565, 0.2761]

optimizer:
  name: SGD
  kwargs:
    lr: 0.1

buffer:
  name: ERBuffer
  kwargs:
    capacity: 10000 # num_classes * M
    input_size: (3, 32, 32)

backbone: 
  name: resnet18
  kwargs:
    args: 
      dataset: cifar100

classifier:
  name: ERAML
  kwargs:
    num_classes: 100
    task_free: False
