includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  - backbones/resnet12.yaml

image_size: 32


save_path: ./
# data
init_cls_num: 50
inc_cls_num: 25
task_num: 3

init_epoch: 1 # 100
epoch: 1 # 100
n_gpu: 1
val_per_epoch: 50


batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [60, 120, 170]

backbone:
  name: cifar_resnet32
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: EWC
  kwargs:
    num_class: 100
    feat_dim: 64
    init_cls_num: 50
    inc_cls_num: 50
    lamda: 1000
