save_path : ""
data_root: "/home/lvqiexuan/temp_data/cifar100/"

init_cls_num: &init_cls_num 10 # 第一次任务的分类数量
inc_cls_num: &inc_cls_num 10   # 之后每次任务的分类数量
total_cls_num: &total_cls_num 100
num_classes: &num_classes 100 
task_num: &task_num 10

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
init_epoch: 20 # 20
epoch: 20 # 20
val_per_epoch: 20
workers: 16

batch_size: 128

device_ids: 0

setting: task-agnostic # not require task id during inference
# or task-aware, require task id during inference

optimizer:
  name: Adam
  kwargs:
    lr: 0.0005
    weight_decay: 0
    betas: [0.9, 0.999]

lr_scheduler:
  name: CosineSchedule
  kwargs:
    K: 20

backbone:
  name: vit_pt_imnet_in21k_lora
  kwargs:
    pretrained: True
    rank: 10
    


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: InfLoRA_OPT
  kwargs:
    init_cls_num: 10
    inc_cls_num: 10
    task_num: 10
    lame: 1.0
    lamb: 0.95
    embd_dim: 768





