init_cls_num: &init_cls_num 20 # 第一次任务的分类数量
inc_cls_num: &inc_cls_num 20   # 之后每次任务的分类数量
total_cls_num: &total_cls_num 100
num_classes: &num_classes 100 
task_num: &task_num 5

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
init_epoch: 2 # 20
epoch: 2 # 20
val_per_epoch: 20
image_size: 224

batch_size: 128

setting: task-agnostic 

optimizer:
  name: Adam
  kwargs:
    lr: 0.0005
    weight_decay: 0
    betas: [0.9, 0.999]

lr_scheduler:
  name: CosineSchedule
  kwargs:
    K: 20

backbone:
  name: vit_pt_imnet
  kwargs:
    pretrained: True
    model_name : vit_base_patch16_224_in21k
    lora_tuning: True
    lora_rank: 10


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: InfLoRA_OPT
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    lame: 1.0
    lamb: 0.95
    embd_dim: 768





