
dataset: &dataset cifar100
init_cls_num: &init_cls_num 10
inc_cls_num: &inc_cls_num 10
total_cls_num: &total_cls_num 100
task_num: &task_num 10
image_size: &image_size 224

init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
task_num: *task_num

epoch: 5 
val_per_epoch: 5

batch_size: 128

train_trfms:
  - Resize:
      size: 256 # Stated in source code of L2P
  - RandomResizedCrop: 
      size: *image_size
  - RandomHorizontalFlip: {}
  - ToTensor: {}

test_trfms: 
  - Resize:
      size: 256 # Stated in source code of L2P
  - CenterCrop: 
      size: *image_size
  - ToTensor: {}

optimizer:
  name: Adam
  kwargs:
    lr: 0.03
    betas: [0.9, 0.999]

lr_scheduler:
  name: Constant

backbone:
  name: vit_pt_imnet
  kwargs:
    num_classes: 100
    pretrained: true
    model_name : vit_base_patch16_224

classifier:
  name: L2P
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    num_class: *total_cls_num
    task_num: *task_num
    feat_dim: 768
    prompt_length: 20 # 20
    pool_size: 30 # 30

