includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  # - backbones/resnet12.yaml

data_root: /data/fanzhichen/continual/cifar100
image_size: 32
save_path: ./
# data
init_cls_num: 10
inc_cls_num: 10
task_num: 10


epoch: 10 #160
device_ids: 4
n_gpu: 1
val_per_epoch: 5


batch_size: 128


optimizer:
  name: Adam
  kwargs:
    lr: 0.001
    betas: [0.9, 0.999]
    weight_decay: 0

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: vit_pt_imnet
  kwargs:
    num_classes: 100
    pretrain: true



buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: L2P
  kwargs:
    num_class: 100
    feat_dim: 768
    task_num: 10
    init_cls_num: 10
    inc_cls_num: 10
    prompt_length: 20
    pool_size: 30

