includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: /data/fanzhichen/continual/cifar100
image_size: 32
  
save_path: ./
# data
init_cls_num: 50
inc_cls_num: 10
task_num: 6


epoch: 160 # 160
device_ids: 1
n_gpu: 1
val_per_epoch: 1


batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.1

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: resnet32
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: LUCIR
  kwargs:
    num_class: 100
    feat_dim: 512
    init_cls_num: 50
    inc_cls_num: 10
    dist: 0.5
    lamda: 5
    K: 2
    lw_mr: 1
