includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  # - headers/optimizer.yaml
  - backbones/resnet12.yaml

image_size: 32
save_path: ./
# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5


epoch: 2 # 160
device_ids: 0
n_gpu: 1
val_per_epoch: 1


batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: resnet32_V2
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100


buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: LUCIR
  kwargs:
    num_class: 100
    feat_dim: 64
    init_cls_num: 20
    inc_cls_num: 20
    dist: 0.5
    lamda: 5
    K: 2
    lw_mr: 1
