dataset: &dataset cifar100
init_cls_num: &init_cls_num 10
inc_cls_num: &inc_cls_num 10
task_num: &task_num 10
epoch: &epoch 5

dataset: *dataset
task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
epoch: *epoch
val_per_epoch: *epoch
workers: 24

batch_size: 128

setting: task-agnostic

optimizer:
  name: Adam
  kwargs:
    lr: 0.0005
    weight_decay: 0.0
    betas: [0.9, 0.999]

lr_scheduler:
  name: CosineSchedule
  kwargs:
    K: *epoch

backbone:
  name: vit_pt_imnet
  kwargs:
    pretrained: True
    model_name: vit_base_patch16_224_in21k
    lora_tuning: True
    lora_rank: 10

classifier:
  name: MoE_Test
  kwargs:
    dataset: *dataset
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    lame: 1.0
    lamb: 0.95
    embd_dim: 768
    use_ca: False





