init_cls_num: &init_cls_num 20 # 第一次任务的分类数量
inc_cls_num: &inc_cls_num 20   # 之后每次任务的分类数量
total_cls_num: &total_cls_num 100
task_num: &task_num 5
image_size: &image_size 224

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
epoch: 1
val_per_epoch: 1
image_size: *image_size

train_batch_size: 128
test_batch_size: 64

testing_times: 10

setting: task-agnostic 

train_trfms:
  - RandomResizedCrop :
      size: *image_size
      scale: [0.9, 1.0]
      interpolation: BICUBIC
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

test_trfms: 
  - Resize :
      size: *image_size
      interpolation: BICUBIC
  - ToTensor: {}
  - Normalize:
      mean: [0.48145466, 0.4578275, 0.40821073]
      std: [0.26862954, 0.26130258, 0.27577711]

optimizer:
  name: AdamW
  kwargs:
    lr: 1e-3
    weight_decay: 0.

lr_scheduler:
  name: CosineAnnealingWarmUp # Might not be exact same as the original
  kwargs:
    T_max: 0 # Will be replaced in trainter.py with epoch * len(dataloader)
    warmup_length: 30

backbone:
  name: clip
  kwargs:
    model_name : ViT-B/16
    pretrained : True

classifier:
  name: MOE_ADAPTER4CL
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    prompt_template : "a bad photo of a {}."
    label_smoothing: 0.
