includes:
  - headers/data.yaml
  - headers/device.yaml
  # - headers/model.yaml
  # - headers/optimizer.yaml
  # - backbones/resnet12.yaml

data_root: /data/fanzhichen/continual/cifar100
image_size: 32

# no warm up
warmup: 0

save_path: ./
# data

init_cls_num: 10
inc_cls_num: 10
task_num: 10


batch_size: 10
epoch: 1
device_ids: 2
n_gpu: 1
val_per_epoch: 1


optimizer:
  name: Adam
  kwargs:
    lr: 0.001
    betas: [0.9, 0.99]
    weight_decay: 0.0001


lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 120



backbone:
  name: resnet18
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100



buffer:
  name: OnlineBuffer
  kwargs:
    buffer_size: 5000
    batch_size: 64
    input_size: [3, 32, 32]
    # strategy: herding     # random, equal_random, reservoir, herding



classifier:
  name: OCM
  kwargs:
    num_class: 100
    feat_dim: 512
    init_cls_num: 10
    inc_cls_num: 10
    task_num: 10