image_size: 32

warmup: 0

# 10-subsets on CiFar100
task_num: 10
init_cls_num: 10 
inc_cls_num: 10 

# 20-subsets on CiFar100
#task_num: 5
#init_cls_num: 20 
#inc_cls_num: 20

batch_size: 10
epoch: 1
n_gpu: 1
val_per_epoch: 1

optimizer:
  name: Adam
  kwargs:
    lr: 0.001
    betas: [0.9, 0.99] # Not stated in paper, but appears in Original Code
    weight_decay: 0.0001

backbone:
  name: resnet18
  kwargs:
    num_classes: 100
    args: 
      dataset: cifar100

buffer:
  name: OnlineBuffer
  kwargs:
    buffer_size: 5000
    batch_size: 64
    input_size: [3, 32, 32]
    # strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: OCM
  kwargs:
    num_class: 100
    feat_dim: 512
    init_cls_num: 10
    inc_cls_num: 10
    task_num: 10