init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 100
num_classes: &num_classes 100 
task_num: &task_num 5

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
init_epoch: 1 # 20
epoch: 1 # 1
batch_size: 48 # 128
val_per_epoch: 20

image_size: 224

optimizer:
  name: SGD
  kwargs:
    momentum: 0.9
    lr: 0.01
    weight_decay: 0.0005

lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 20
    eta_min: 0.0

backbone:
  name: vit_pt_imnet_in21k_adapter
  kwargs:
    pretrained: true
    model_name : vit_base_patch16_224_in21k

classifier:
  name: RanPAC
  kwargs:
    use_RP: True
    M: 10000
    first_session_training: True
    init_cls_num: *init_cls_num
    inc_cls_num: *inc_cls_num
    task_num: *task_num
    total_cls_num: *total_cls_num
    embd_dim: 768
