save_path : ""
data_root: "/home/lvqiexuan/temp_data/cifar100/"

init_cls_num: &init_cls_num 20
inc_cls_num: &inc_cls_num 20
total_cls_num: &total_cls_num 100
num_classes: &num_classes 100 
task_num: &task_num 5

task_num: *task_num
init_cls_num: *init_cls_num
inc_cls_num: *inc_cls_num
total_cls_num: *total_cls_num
init_epoch: 2 # 200
epoch: 2 # 200
batch_size: 64 
val_per_epoch: 200

setting: task-aware

optimizer:
  name: SGD
  kwargs:
    lr: 0.01

lr_scheduler:
  name: PatienceSchedule
  kwargs:
    patience: 6
    factor: 2
    stopping_lr: 1e-5

backbone:
  name: AlexNet_TRGP
  kwargs:

buffer:
  name: LinearBuffer
  kwargs:
    buffer_size: 0
    batch_size: 128
    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: TRGP
  kwargs:
    init_cls_num: *init_cls_num
    inc_cls_num: *init_cls_num
    task_num: *task_num
