includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml

# Set paths to datasets
data_root: ${DATASET_DIR}/cifar100

# Image size
image_size: 32

save_path: ./

# Data settings
init_cls_num: 20
inc_cls_num: 20
task_num: 5

# Training setting
init_epoch: 250
epoch: 250
device_ids: 0
n_gpu: 1
val_per_epoch: 1
batch_size: 128

# Optimizer settings
optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    weight_decay: 2e-4
    momentum: 0.9

# Learning rate scheduler settings
lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

# Backbone architecture settings
backbone:
  name: cifar_resnet32
  kwargs:
    num_classes: 100
    args:
      dataset: cifar100

# Buffer settings
buffer:
  name: LinearHerdingBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
#    strategy: herding     # random, equal_random, reservoir, herding

# Classifier settings
classifier:
  name: WA
  kwargs:
    num_class: 100
    feat_dim: 64
    init_cls_num: 20
