includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet12.yaml

data_root: /data/fanzhichen/continual/cifar100
image_size: 32

save_path: ./
# data
init_cls_num: 20
inc_cls_num: 20
task_num: 5


init_epoch: 250 # PyCIL: 200
epoch: 250 # PyCIL: 170
device_ids: 0
n_gpu: 1
val_per_epoch: 1
batch_size: 128


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    weight_decay: 2e-4
    momentum: 0.9

lr_scheduler:
  name: MultiStepLR
  kwargs:
    gamma: 0.1
    milestones: [80, 120]

backbone:
  name: resnet32_wa
  kwargs:
    num_classes: 100
    args:
      dataset: cifar100


buffer:
  name: LinearHerdingBuffer
  kwargs:
    buffer_size: 2000
    batch_size: 128
#    strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: WA
  kwargs:
    num_class: 100
    feat_dim: 512
